const ACTION_TYPE = {
    USER_SIGN_IN: "USER_SIGN_IN",
    LOADING_SPNNER: "LOADING_SPNNER",
    SIGN_WITH_GOOGLE: "SIGN_WITH_GOOGLE",
    LOGIN_USER: "LOGIN_USER",
    FORGET_PASSWORD: "FORGET_PASSWORD",
    FORGET_PASSWORD_REQUIEST: "FORGET_PASSWORD_REQUIEST",
    MOVIE_UPLOAD: "MOVIE_UPLOAD",
    GET_ALL_MOVIES: "GET_ALL_MOVIES",
    OVER_LAY_DIV: "OVER_LAY_DIV",
    TOGGLE_POPUP: "TOGGLE_POPUP",
    SHOW_OPTIONS_POPUP: "SHOW_OPTIONS_POPUP",
    CHANGE_THEME: "CHANGE_THEME",
    SELECTED_MOVIE: "SELECTED_MOVIE",
    STREM_VIDEOS: "STREM_VIDEOS",
    USER_HISTORY: "USER_HISTORY",
    REMOVER_USER_ONE_HISTORY_MOVIE: "REMOVER_USER_ONE_HISTORY_MOVIE",
};

export default ACTION_TYPE;
