const ACTION_TYPE = {
    USER_SIGN_IN: "USER_SIGN_IN",
    LOADING_SPNNER: "LOADING_SPNNER",
    SIGN_WITH_GOOGLE: "SIGN_WITH_GOOGLE",
    LOGIN_USER: "LOGIN_USER",
    FORGET_PASSWORD: "FORGET_PASSWORD",
    FORGET_PASSWORD_REQUIEST: "FORGET_PASSWORD_REQUIEST",
    MOVIE_UPLOAD: "MOVIE_UPLOAD",
};

export default ACTION_TYPE;
